### ISSUE TITLE
Can I use this on my own server

### ISSUE THREAD

**Issue by DisarmingForces** [Fallingsheep1985/Arma3Epoch#1]

**Comment by fallingsheep** [comment]
yes its publicly open be aware there may be issues/bugs as its under testing and development, more features will be added to it as time goes by

**Comment by DisarmingForces** [comment]
Ok just uploaded it without the anti hack and it wont load my epoch it just says starting epoch please wait any thoughts.

**Comment by Fallingsheep1985** [comment]
Please note it has infistar on it which was included in the files I t is out of date and probably should be removed

Sent by Outlookhttp://taps.io/outlookmobile for Android

On Wed, Feb 18, 2015 at 4:36 PM -0800, "fallingsheep" <notifications@github.com<mailto:notifications@github.com>> wrote:

yes its publicly open be aware there may be issues/bugs as its under testing and development, more features will be added to it as time goes by

**Comment by Fallingsheep1985** [comment]
I can't check it I'm at work, I'll remove infistar tonight and test the push a working commit for you to try

Sent by Outlookhttp://taps.io/outlookmobile for Android

On Wed, Feb 18, 2015 at 4:39 PM -0800, "DisarmingForces" <notifications@github.com<mailto:notifications@github.com>> wrote:

Ok just uploaded it without the anti hack and it wont load my epoch it just says starting epoch please wait any thoughts.

**Comment by DisarmingForces** [comment]
Ok thanks and no problem take your time with it was just wondering if you new. Thanks for allowing me to use Your modded epoch.

**Comment by fallingsheep** [comment]
no probs it will be released on opendayz as my new repack once ive added the new features and tested it

PS: Fallingsheep1985 is also me its my second account for at home use so ican tellwhat was done at home and what was done at work :)

**Comment by DisarmingForces** [comment]
ok thanks

**Comment by DisarmingForces** [comment]
Sorry to bother you again but, it would also be nice if you could upload the battleye filters Please, Thanks again for your time.

**Comment by fallingsheep** [comment]
i dont use battle ey at the moment i couldnt get watchdog working with epoch, as i said this is still in development

**Comment by DisarmingForces** [comment]
ok

**Comment by DisarmingForces** [comment]
I'm going to start working on battleye filters myself for this and if you want I can send you them when I'm done. Don't have much off time but will try to get them done soon.
